"""empty message

Revision ID: 6baa1f4fac7d
Revises: 
Create Date: 2021-12-10 19:34:06.736938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6baa1f4fac7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL-crawl-url',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_TBL-crawl-url_url'), 'TBL-crawl-url', ['url'], unique=False)
    op.create_table('TBL-crawler',
    sa.Column('ID_session', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_internal_url', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ID_session', 'url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBL-crawler')
    op.drop_index(op.f('ix_TBL-crawl-url_url'), table_name='TBL-crawl-url')
    op.drop_table('TBL-crawl-url')
    # ### end Alembic commands ###
